### ISSUE TITLE
你好，我训练hrsc后，测试的可视化里检测框都是平行四边形，而不是像标签那样的旋转矩形，请问是怎么回事呢

### ISSUE THREAD

**Issue by 18804601171** [yijingru/BBAVectors-Oriented-Object-Detection#41]

**Comment by yijingru** [comment]
It's a result of affine transformation when the output aspect ratio is different from the training images.

**Comment by 18804601171** [comment]
@yijingru 那怎么能让检测结果是正常的旋转矩形呢，因为我训练完dota后，测试的时候，我看检测的可视化里检测框基本都是正常的旋转矩形呢

**Comment by yijingru** [comment]
Because dota is from cropped images, whose aspect ratio is 1

**Comment by hust-kevin** [comment]
@18804601171 你知道怎么让hrsc的可视化是正常的嘛

**Comment by heyun1994** [comment]
@18804601171我也遇到了这个问题，我用自己的数据集没有裁剪成600*600，检测结果也是平行四边形，请问你解决了吗？
 @yijingru 不太明白你回答的，可以详细说下吗？

**Comment by yijingru** [comment]
图片宽高比的问题，1:1就是矩形

**Comment by heyun1994** [comment]
那我应该怎么做才能是矩形呢？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yijingru/BBAVectors-Oriented-Object-Detection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月21日(星期六) 下午2:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yijingru/BBAVectors-Oriented-Object-Detection] 你好，我训练hrsc后，测试的可视化里检测框都是平行四边形，而不是像标签那样的旋转矩形，请问是怎么回事呢 (#41)





 
图片宽高比的问题，1:1就是矩形
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yijingru** [comment]
1. 保持training和testing图片宽高比一致，使用padding?
2. 或者修改decoding box方式？强行转换矩形，比如找平行边垂直线，同时穿过对边的检测点。如果有此类算法，欢迎分享！
